[package]
name = "deathfloor"
version = "0.0.0"
authors = ["Noah Rosenzweig <rosenzweig.noah@gmail.com>"]
edition = "2018"
readme = "./README.md"
license = "MIT"

[dependencies]
ron = "0.5.1"
serde_json = "1.0.44"
specs-derive = "0.4.0"
derive_builder = "0.9.0"

[dependencies.deathfloor_derive]
version = "*"
path = "./deathfloor_derive"

[dependencies.deathframe]
version = "*"
path = "../deathframe"
# git = "https://github.com/Noah2610/deathframe"
# branch = "develop"
features = [
    "vulkan",
    "serde",
    "physics",
    "animation",
]

[dependencies.serde]
version = "1.0.104"
features = ["derive"]

[features]
default = []
debug = ["deathframe/debug"]
nightly = ["deathframe/nightly"]
