[package]
name = "deathfloor"
version = "0.0.0"
authors = ["Noah Rosenzweig <rosenzweig.noah@gmail.com>"]
edition = "2018"
readme = "./README.md"
license = "MIT"

[dependencies]
ron = "0.5.1"
specs-derive = "0.4.0"

[dependencies.deathframe]
git = "https://github.com/Noah2610/deathframe"
branch = "develop"
features = ["vulkan"]

[features]
default = []
nightly = ["deathframe/nightly"]
