[package]
name = "deathfloor"
version = "0.0.0"
authors = ["Noah Rosenzweig <rosenzweig.noah@gmail.com>"]
edition = "2018"
readme = "./README.md"

[dependencies]
deathframe = "0.5.1"

[dependencies.amethyst]
git = "https://github.com/amethyst/amethyst"
rev = "8c022f464e3d17a4b997cad83c5a1a62c7289ace"
default-features = false
# features = ["animation", "audio", "locale", "network", "renderer"]
features = ["audio", "renderer", "vulkan"]

[features]
default = []
nightly = ["amethyst/nightly"]
